// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM1SwPyVKe3wuJMyQ1LZBaX12Lv5MluY0',
    appId: '1:656563662547:web:1325976337a7d3dc58ae26',
    messagingSenderId: '656563662547',
    projectId: 'etaa-490ca',
    authDomain: 'etaa-490ca.firebaseapp.com',
    storageBucket: 'etaa-490ca.firebasestorage.app',
    measurementId: 'G-QSXSJCQ7GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR5lPY5werNEQGarIkI46sCbbpm6Pt0E8',
    appId: '1:656563662547:android:3fa7dbb99b81c7ae58ae26',
    messagingSenderId: '656563662547',
    projectId: 'etaa-490ca',
    storageBucket: 'etaa-490ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfsb_SudkqnacWSIBYGSF63Ht8HcAeDPE',
    appId: '1:656563662547:ios:da9327c859858db258ae26',
    messagingSenderId: '656563662547',
    projectId: 'etaa-490ca',
    storageBucket: 'etaa-490ca.firebasestorage.app',
    iosBundleId: 'com.example.eataa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfsb_SudkqnacWSIBYGSF63Ht8HcAeDPE',
    appId: '1:656563662547:ios:da9327c859858db258ae26',
    messagingSenderId: '656563662547',
    projectId: 'etaa-490ca',
    storageBucket: 'etaa-490ca.firebasestorage.app',
    iosBundleId: 'com.example.eataa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM1SwPyVKe3wuJMyQ1LZBaX12Lv5MluY0',
    appId: '1:656563662547:web:809a1698148c2bf258ae26',
    messagingSenderId: '656563662547',
    projectId: 'etaa-490ca',
    authDomain: 'etaa-490ca.firebaseapp.com',
    storageBucket: 'etaa-490ca.firebasestorage.app',
    measurementId: 'G-2JPD8TVRS2',
  );
}
